# Generated by Django 5.1.3 on 2024-11-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=45)),
                ('student_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpop', models.BooleanField(default=False)),
                ('jpop', models.BooleanField(default=False)),
                ('pop', models.BooleanField(default=False)),
                ('hard_rock', models.BooleanField(default=False)),
                ('indie', models.BooleanField(default=False)),
                ('ballad', models.BooleanField(default=False)),
                ('funk', models.BooleanField(default=False)),
                ('rnb', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubmanage.user')),
            ],
        ),
    ]
