# Generated by Django 5.1.3 on 2024-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('song1', models.CharField(max_length=45)),
                ('song2', models.CharField(blank=True, max_length=45, null=True)),
                ('vocal', models.CharField(blank=True, max_length=45, null=True)),
                ('guitar', models.CharField(blank=True, max_length=45, null=True)),
                ('second_guitar', models.CharField(blank=True, max_length=45, null=True)),
                ('bass', models.CharField(blank=True, max_length=45, null=True)),
                ('drum', models.CharField(blank=True, max_length=45, null=True)),
                ('keyboard', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAvailabledate',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mon', models.IntegerField(blank=True, null=True)),
                ('tue', models.IntegerField(blank=True, null=True)),
                ('wed', models.IntegerField(blank=True, null=True)),
                ('thu', models.IntegerField(blank=True, null=True)),
                ('fri', models.IntegerField(blank=True, null=True)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('sun', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_availabledate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('vocal', models.CharField(blank=True, max_length=7, null=True)),
                ('guitar', models.CharField(blank=True, max_length=7, null=True)),
                ('bass', models.CharField(blank=True, max_length=7, null=True)),
                ('drum', models.CharField(blank=True, max_length=7, null=True)),
                ('keyboard', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userprefergenre',
            options={'managed': False},
        ),
    ]
